version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./Mongodb-mount:/data/db
    networks:
      mongonet:
        ipv4_address: 10.0.77.7
    ports:
      - "27017:27017"

networks:
  mongonet:
    driver: bridge
    ipam: 
      config:
        - subnet: 10.0.77.0/24
          gateway: 10.0.77.1

